alias: Arlo On if away during the day
initial_state: 'on'
trigger:
  - platform: state
    entity_id: device_tracker.oneplus
    to: 'not_home'
condition:
  condition: and
  conditions:
    - condition: time
      after: '9:00'
      before: '21:00'
    - condition: state
      entity_id: input_boolean.arlo_state
      state: 'off'
action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.arlo_state

