alias: Arlo Hass Start arm
initial_state: 'on'
trigger:
  - platform: homeassistant
    event: start
action:
  - service: aarlo.alarm_set_mode
    data:
      entity_id: alarm_control_panel.aarlo_hayward_arlo
      mode: 'armed'
