alias: Arlo Off if Home during the day
initial_state: 'on'
trigger:
  - platform: state
    entity_id: device_tracker.oneplus
    to: 'home'
condition:
  condition: and
  conditions:
    - condition: time
      after: '9:00'
      before: '21:00'
    - condition: state
      entity_id: input_boolean.arlo_state
      state: 'on'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.arlo_state

