alias: Stairs On via Sensor During the Day
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.stairs_sensor_down_motion
    to: 'on'
  - platform: state
    entity_id: binary_sensor.stairs_sensor_up_motion
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: time
      after: '8:00'
      before: '1:00'
    - condition: template
      value_template: '{{ ((float(states("sensor.stairs_sensor_down_light_level")) + float(states("sensor.stairs_sensor_up_light_level"))) / 2) | round (2) < 3.5}}'
action:
  - service: hue.hue_activate_scene
    data:
      group_name: "Stairs"
      scene_name: "Relax"
  - service: timer.start
    data:
      entity_id: timer.stairs


